"""Git executor (§72–74): branch, bounded patch, commit, push, PR.

`git.open_pr` does not shell out to GitHub in the core — it emits the
PR *spec* (title/body/head/base + plan-hash trailer). The transport may
be `gh pr create` host-side; the body carries reason, evidence, deltas,
risk, validation, rollback per §74. Force-push is never generated;
`--force-with-lease` only on pf/* branches and only when requested.
"""

from __future__ import annotations

from typing import Any

from platformforge.ops.executors.base import Executor


class GitExecutor(Executor):
    name = "git"

    def argv_for(self, action: str, params: dict[str, Any],
                 dry_run: bool) -> list[str] | dict[str, Any]:
        repo = params.get("repo", ".")
        if action == "git.create_branch":
            base = params.get("base", "HEAD")
            return ["git", "-C", repo, "checkout", "-b", params["branch"], base]
        if action == "git.apply_patch":
            if params.get("check_only") or dry_run:
                return ["git", "-C", repo, "apply", "--check", "--index",
                        "-"]      # patch content via stdin host-side
            return ["git", "-C", repo, "apply", "--index",
                    "--whitespace=error-all", "-"]
        if action == "git.commit":
            argv = ["git", "-C", repo, "commit", "-m", params["message"]]
            if params.get("signoff"):
                argv.append("--signoff")
            return argv
        if action == "git.push":
            remote = params.get("remote", "origin")
            return ["git", "-C", repo, "push", "-u", remote,
                    params["branch"]]
        if action == "git.open_pr":
            # PR is a host integration — emit spec; transport runs gh/api
            return ["pr-spec", params["repo"], params["head"],
                    params["base"], params["title"]]
        if action == "git.delete_branch":
            return ["git", "-C", repo, "branch", "-D", params["branch"]]
        if action == "git.revert_commit":
            return ["git", "-C", repo, "revert", "--no-edit",
                    params["commit_sha"]]
        if action == "git.close_pr":
            return ["pr-close", params["repo"], str(params["pr"])]
        return super().argv_for(action, params, dry_run)


def pr_body(*, reason: str, evidence: list[str], plan_hash: str,
            expected_delta: dict[str, Any], risk: dict[str, Any],
            validation: list[str], rollback: dict[str, Any]) -> str:
    """§74 — generated PRs carry the full evidence chain."""
    lines = [f"## Reason\n{reason}", "",
             "## Evidence",
             *[f"- {e}" for e in evidence], "",
             f"Plan hash: `{plan_hash}`", "",
             "## Expected delta",
             "```json",
             _j(expected_delta), "```", "",
             "## Risk", "```json", _j(risk), "```", "",
             "## Validation", *[f"- {v}" for v in validation], "",
             "## Rollback", "```json", _j(rollback), "```", "",
             "---",
             "Generated by Platform Forge (governed operations).",
             f"Plan-Hash: {plan_hash}"]
    return "\n".join(lines)


def _j(obj: Any) -> str:
    import json
    return json.dumps(obj, indent=2, sort_keys=True)[:4000]
