"""GitOps executor (§79–81): ArgoCD sync/diff/wait/rollback.

GitOps-first: the default remediation path is a Git change the
controller reconciles. `argocd.sync` exists for governed cases only —
it requires application scope, pinned revision, diff evidence, health
precondition, policy allow and approval. `--prune`, `--replace`,
`--force` are never generated by the executor: they are distinct,
higher-risk capabilities requiring their own envelopes.
"""

from __future__ import annotations

from typing import Any

from platformforge.ops.executors.base import Executor


class ArgoCDExecutor(Executor):
    name = "argocd"

    def argv_for(self, action: str, params: dict[str, Any],
                 dry_run: bool) -> list[str] | dict[str, Any]:
        a = action.split(".", 1)[1]
        app = params.get("app", "")
        if a == "diff":
            argv = ["argocd", "app", "diff", app]
            if params.get("revision"):
                argv += ["--revision", params["revision"]]
            argv += ["--hard-refresh"]
            return argv
        if a == "sync":
            argv = ["argocd", "app", "sync", app]
            if params.get("revision"):
                argv += ["--revision", params["revision"]]
            for r in params.get("resource", []) or []:
                argv += ["--resource", r]
            if dry_run or params.get("dry_run"):
                argv += ["--dry-run"]
            # §81 guards — prune/replace/force are never emitted here
            return argv
        if a == "wait":
            argv = ["argocd", "app", "wait", app, "--health", "--sync"]
            argv += ["--timeout", str(params.get("timeout_s", 300))]
            return argv
        if a == "rollback":
            argv = ["argocd", "app", "rollback", app]
            if params.get("history_id"):
                argv += [str(params["history_id"])]
            return argv
        return super().argv_for(action, params, dry_run)


class KubernetesExecutor(Executor):
    """§82–83 — narrow actions only: scale, rollout restart/undo,
    controlled annotate, rollout status. Every write binds
    resourceVersion/uid preconditions when supplied; arbitrary object
    patch does not exist."""

    name = "kubernetes"

    def argv_for(self, action: str, params: dict[str, Any],
                 dry_run: bool) -> list[str] | dict[str, Any]:
        a = action.split(".", 1)[1]
        kind, name = params.get("kind", ""), params.get("name", "")
        target = f"{kind}/{name}"
        ns = []
        if params.get("namespace"):
            ns = ["-n", params["namespace"]]
        if params.get("context"):
            ns += ["--context", params["context"]]
        dr = ["--dry-run=server"] if dry_run else []

        if a == "scale":
            argv = ["kubectl", "scale", target,
                    "--replicas", str(params["replicas"])] + ns
            if params.get("current_replicas") is not None:
                argv += ["--current-replicas",
                         str(params["current_replicas"])]
            if params.get("resource_version"):
                argv += ["--resource-version",
                         str(params["resource_version"])]
            return argv + dr
        if a == "rollout_restart":
            return ["kubectl", "rollout", "restart", target] + ns + dr
        if a == "rollout_undo":
            argv = ["kubectl", "rollout", "undo", target] + ns
            if params.get("to_revision"):
                argv += ["--to-revision", str(params["to_revision"])]
            return argv + dr
        if a == "rollout_status":
            argv = ["kubectl", "rollout", "status", target] + ns
            argv += ["--timeout", f"{params.get('timeout_s', 300)}s"]
            argv += ["--watch=false"]
            return argv
        if a == "annotate":
            anns = params.get("annotations", {})
            rems = params.get("remove_annotations", []) or []
            if not isinstance(anns, dict) or (not anns and not rems):
                return {"refusal": "PF-OPS-ANNOTATE-EMPTY",
                        "unlock": "annotations or remove_annotations "
                                  "must be non-empty"}
            safe = {k: str(v) for k, v in anns.items()
                    if _annotation_allowed(k)}
            safe_rems = [k for k in rems if _annotation_allowed(k)]
            if len(safe) != len(anns) or len(safe_rems) != len(rems):
                return {"refusal": "PF-OPS-ANNOTATE-UNSAFE",
                        "unlock": "only platformforge.io/*, "
                                  "ops.platformforge.io/* annotations "
                                  "or whitelisted keys are writable"}
            argv = ["kubectl", "annotate", target] + ns
            argv += [f"{k}={v}" for k, v in safe.items()]
            argv += [f"{k}-" for k in safe_rems] + ["--overwrite"]
            if params.get("resource_version"):
                # optimistic concurrency via JSON patch precondition
                argv = ["kubectl", "patch", target, "--type=json",
                        "-p", '[{"op":"test","path":"/metadata/'
                              'resourceVersion","value":"'
                        + str(params["resource_version"]) + '"}]'] + ns
                return argv + dr
            return argv + dr
        return super().argv_for(action, params, dry_run)


_ANNOTATION_PREFIXES = ("platformforge.io/", "ops.platformforge.io/",
                        "pf.io/")


def _annotation_allowed(key: str) -> bool:
    return key.startswith(_ANNOTATION_PREFIXES)


EXECUTORS = {"git": "GitExecutor", "terraform": "TerraformExecutor",
             "tofu": "TofuExecutor", "argocd": "ArgoCDExecutor",
             "kubernetes": "KubernetesExecutor"}
